---

- name: Ensure database user exists
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name={{ db_user }}
    password={{ db_pass }}
    encrypted=True
  notify: restart postgres

- name: Ensure application database exists
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name={{ db_name }}
    owner={{ db_user }}
    encoding="UTF-8"
    lc_collate="pt_BR.UTF-8"
    lc_ctype="pt_BR.UTF-8"
    template="template0"
    state=present
  notify: restart postgres
