---

djangoapp_name: blacklist
djangoapp_user: blacklist
djangoapp_group: webapps
djangoapp_project_module: blacklist
djangoapp_base_dir: "{{ djangoapp_source_dir }}/src"
djangoapp_repo_url: git@github.com:tcosta84/blacklist.git
djangoapp_enable_celery: true
djangoapp_enable_celerybeat: true
djangoapp_enable_flower: true

gunicorn_max_requests: 0
celery_autoreload: false

postgres_listen_addresses: "*"
postgres_db_pass_encrypted: true
postgres_db_encoding: UTF-8
postgres_db_lc_collate: pt_BR.UTF-8
postgres_db_lc_ctype: pt_BR.UTF-8
postgres_db_template: template0
postgres_db_name: blacklist
postgres_db_user: postgres
postgres_db_pass: md53175bce1d3201d16594cebf9d7eb3f9d
postgres_pg_hba_custom:
  - { type: host, database: blacklist, user: postgres, address: 0.0.0.0/0, method: md5 }

rabbitmq_management_plugin: true
rabbitmq_remove_guest_user: true
rabbitmq_host: localhost
rabbitmq_port: 5672
rabbitmq_admin_user: admin
rabbitmq_admin_pass: 12345
rabbitmq_app_user: blacklist
rabbitmq_app_pass: 12345
rabbitmq_app_vhost: blacklist
    
supervisor_web_host: "{{ inventory_hostname }}"
supervisor_web_port: 9001
supervisor_web_user: admin
supervisor_web_pass: 12345
