---

djangoapp_envvars:
  DEBUG: True
  SECRET_KEY: ypfj76g@yp#f7b$u&-1w1+&715$mqu^z4u^o6g1^q2uhv3vblt
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/blacklist
  MEMCACHED_LOCATION: localhost:11211
  RABBITMQ_URL: amqp://guest@localhost//
  STATIC_ROOT: "{{ djangoapp_static_dir }}"
  MEDIA_ROOT: "{{ djangoapp_media_dir }}"
  LOGGING_ROOT: "{{ djangoapp_logs_dir }}"

gunicorn_max_requests: "1"
celery_autoreload: "true"
