---

djangoapp_envvars:
  DEBUG: False
  ALLOWED_HOSTS: "*"
  SECRET_KEY: ypfj76g@yp#f7b$u&-1w1+&715$mqu^z4u^o6g1^q2uhv3vblt
  DATABASE_URL: postgres://postgres:postgres@104.131.96.178:5432/blacklist
  MEMCACHED_LOCATION: localhost:11211
  RABBITMQ_URL: amqp://{{ rabbitmq_app_user }}:{{ rabbitmq_app_pass }}@{{ rabbitmq_host }}:{{ rabbitmq_port }}/{{ rabbitmq_app_vhost }}
  STATIC_ROOT: "{{ djangoapp_static_dir }}"
  MEDIA_ROOT: "{{ djangoapp_media_dir }}"
  LOGGING_ROOT: "{{ djangoapp_logs_dir }}"
